networks:
  - name: external
    bridge: brext
    address: 192.168.23.1
    netmask: 255.255.255.0

  - name: overcloud
    bridge: brovc

virthost: localhost
libvirt_volume_pool: slitherin
libvirt_uri: qemu:///system
libvirt_volume_path: /home/stack/slitherin
working_dir: /home/stack
image_cache_dir: /home/stack/imgcache
undercloud_image_url: https://images.rdoproject.org/newton/cbs/cloudsig-stable/stable/undercloud.qcow2
overcloud_image_url: https://images.rdoproject.org/newton/cbs/cloudsig-stable/stable/overcloud-full.tar
ipa_image_url: https://images.rdoproject.org/newton/cbs/cloudsig-stable/stable/ironic-python-agent.tar
ansible_user: stack


# Deploy an HA openstack environment.
#
# This will require (6144 * 4) == approx. 24GB for the overcloud
# nodes, plus another 8GB for the undercloud, for a total of around
# 32GB.
control_memory: 6144
compute_memory: 6144

undercloud_memory: 8192

# Giving the undercloud additional CPUs can greatly improve heat's
# performance (and result in a shorter deploy time).
undercloud_vcpu: 4

# Since HA has more machines, we set the cpu for controllers and
# compute nodes to 1
default_vcpu: 2

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
# undercloud_generate_service_certificate: True

# Create three controller nodes and one compute node.
overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230

  - name: compute_0
    flavor: compute
    virtualbmc_port: 6231


# We don't need introspection in a virtual environment (because we are
# creating all the "hardware" we really know the necessary
# information).
step_introspect: false

# Tell tripleo about our environment.
network_isolation: true
extra_args: >-
  --ntp-server pool.ntp.org
test_ping: true
# enable_pacemaker: true

run_tempest: false

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
